---
galaxy_info:
  role_name: caddy_webserver
  author: Your Name
  description: Deploy Caddy web server with Hugo static site generator
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - web
    - caddy
    - hugo
    - webserver
    - staticsite
    - gitdeploy

dependencies: []
